volumeMounts:
  - name: grafana-datasources
    mountPath: /etc/grafana/provisioning/datasources
  - name: grafana-dashboards
    mountPath: /etc/grafana/provisioning/dashboards
  - name: dashboard-files
    mountPath: /var/lib/grafana/dashboards

volumes:
  - name: grafana-datasources
    configMap:
      name: grafana-datasource
  - name: grafana-dashboards
    configMap:
      name: grafana-dashboard-config
  - name: dashboard-files
    configMap:
      name: grafana-dashboard-json
