apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: 127.0.0.1
  ports:
    - port: 9000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
