apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
        - name: cloud-config
          image: camilobueno/cloud-config:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9296